# Generated by Django 2.0.1 on 2018-02-12 00:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkproblem',
            name='s',
        ),
        migrations.AddField(
            model_name='checkproblem',
            name='actions',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), null=True, size=None),
        ),
    ]
