# Generated by Django 2.0.1 on 2018-02-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20180210_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkproblem',
            name='expression1',
        ),
        migrations.RemoveField(
            model_name='checkproblem',
            name='expression2',
        ),
        migrations.AddField(
            model_name='checkproblem',
            name='solution',
            field=models.TextField(null=True),
        ),
    ]
