# Generated by Django 2.0.1 on 2018-02-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_checkproblem_use_btn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkproblem',
            name='use_btn',
        ),
    ]
