# Generated by Django 2.0.1 on 2018-02-12 05:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20180212_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkproblem',
            name='actions',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[['f', 'f']], size=None),
        ),
    ]
